### ISSUE TITLE
Longitude / Latitude Column Size

### ISSUE THREAD

**Issue by gobalopper** [Googer/Professor-Pine-old#13]
Pittsburgh is 40.4406° N, 79.9959° W but long/lat values aren't restricted to just 2 digits before the decimal place. Where I live we have 3 digits before the decimal. To get around this I've made the database columns DECIMAL(9,6) instead of DECIMAL(8,6). Would that cause problems anywhere else in the code?

**Comment by Googer** [comment]
Oops. 😛 I believe that shouldn't be an issue and in fact that would be the correct precision to set on it, but I'll want to double-check that to be absolutely sure.

**Comment by Googer** [comment]
The important part should actually be the scale, since what's actually needed to store location coordinates at full precision as they come from Niantic's actual data, 6 places are needed after the decimal separator.

**Comment by Googer** [comment]
Fixed this in the GymReader repo. 🙂
